### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by sbatchu0108** [vint21h/nagios-check-hddtemp#1]
Unable to Install nagios-check-hddtemp

Error in nagios-check-hddtemp setup command: package_data must be a dictionary mapping package names to lists of wildcard patterns

Install Log:
</code>

pip install nagios-check-hddtemp
Downloading/unpacking nagios-check-hddtemp
  Downloading nagios-check-hddtemp-0.6.0.tar.gz
  Running setup.py egg_info for package nagios-check-hddtemp
    error in nagios-check-hddtemp setup command: package_data must be a dictionary mapping package names to lists of wildcard patterns
    Complete output from command python setup.py egg_info:
    error in nagios-check-hddtemp setup command: package_data must be a dictionary mapping package names to lists of wildcard patterns

---

Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-root/nagios-check-hddtemp
Storing complete log in /root/.pip/pip.log

<code/>

**Comment by vint21h** [comment]
Try new version.
