### ISSUE TITLE
performance data?

### ISSUE THREAD

**Issue by keith4** [vint21h/nagios-check-hddtemp#2]
Any plans to add perf data to this plugin? If not, I can try to hack it in and do a PR, but python isn't exactly where I'm a ninja.

**Comment by vint21h** [comment]
Hello, what type of perf data you think must return this plugin?
I think about 3 variants:
1. hddtemp daemon response get time - IMHO useless
2. hdd temperature - only when check one device
3. hdd temperature in percents relatively to warning and critical
temperature  - only when check one device

**Comment by keith4** [comment]
Maybe option 2, but it should be for all devices?

The performance data spec allows multiple items to be returned, with
thresholds.

For example, the stock check_disk plugin will return perfdata for every
disk:

/=7524MB;8024;9027;0;10031 /dev=0MB;8;9;0;10 /run=0MB;316;356;0;396
/run/lock=0MB;4;4;0;5 /run/shm=0MB;961;1081;0;1202
/var/cache=5MB;204;230;0;256 /var/spool=246MB;204;230;0;256

The spec is available online:
https://nagios-plugins.org/doc/guidelines.html#AEN200

There are some examples in the Nagios docs as well:
https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/pluginapi.html

I'd be happy to test and/or debug if that's helpful.

Let me know what you think.

~Keith

**Comment by vint21h** [comment]
Hello, sorry for long time of answer, i only yesterday return from long
time hackathon.
I think i can implement return perfdata like this:
OK: device /dev/sdb is functional and stable 34C, device /dev/sdc is
functional and stable 40C, device /dev/sda is functional and stable 34C
| /dev/sdb=34, /dev/sdc=40, /dev/sda=34

**Comment by keith4** [comment]
This is good, but use semicolons instead of commas

| /dev/sdb=34; /dev/sdc=40; /dev/sda=34;

~Keith

**Comment by vint21h** [comment]
Try code from 'dev' branch. Run script with '-P' arg. If it works please
report me.

**Comment by keith4** [comment]
yes, perfect! thanks

~Keith

**Comment by vint21h** [comment]
Up version to 0.8.1
